C:\Users\Admin\PycharmProjects\Python_lesson\env\Scripts\python.exe C:/Users/Admin/PycharmProjects/Python_lesson/check_db_connection.py
GET CONNECTION FROM THE LOCAL POOL
Traceback (most recent call last):
SELECT `g`.`group_id`, `g`.`group_name`, `g`.`group_header`, `g`.`group_footer`
FROM `group_list` `g`
WHERE `g`.`group_id` = %s
['11']
  File "C:/Users/Admin/PycharmProjects/Python_lesson/check_db_connection.py", line 11, in <module>

ROLLBACK
    l = db.get_contacts_in_group(Group(id="11"))
RELEASE CONNECTION
  File "<string>", line 2, in get_contacts_in_group
  File "C:\Users\Admin\PycharmProjects\Python_lesson\env\lib\site-packages\pony\orm\core.py", line 533, in new_func
    result = func(*args, **kwargs)
  File "C:\Users\Admin\PycharmProjects\Python_lesson\fixture\orm.py", line 53, in get_contacts_in_group
    orm_group = list(select(g for g in ORMFixture.ORMGroup if g.id == group.id))[0]
IndexError: list index out of range

Process finished with exit code 1
